version: '3'

services:

# ======================================================================
# Load Balance
# ======================================================================

  balance:
    image: nginx:1.16.0-alpine
    container_name: docker-balance
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./vhosts:/etc/nginx/conf.d/vhosts
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/example.com.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - frontend_network

# ======================================================================
# Language
# ======================================================================

  php7fpm1:
    image: codestep/php7phalcon:7.3.7
    container_name: docker-php7fpm1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./../.core:/usr/share/nginx/html/.core
      - ./../example.com-main:/usr/share/nginx/html/main
      - ./conf.d/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - frontend_network

# ======================================================================
# Web Server
# ======================================================================

  main:
    image: nginx:1.16.0-alpine
    container_name: docker-main
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
     - VIRTUAL_HOST=localhost
     - VIRTUAL_PORT=8000
     - NGINX_HOST=location
     - NGINX_PORT=8000
     - TERM=xterm
    volumes:
      - ./../.core:/usr/share/nginx/html/.core
      - ./../example.com-main:/usr/share/nginx/html/main
      - ./webserver/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/sites/main.example.com.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm1:phpfpm"
    ports:
      - "8000:80"
    networks:
      - frontend_network

networks:
  frontend_network:
  #   name: frontend_network
  #   driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24