{% extends '../../../../themes/main/layouts/base.phtml' %}

{% block scriptHeader %} {% endblock %}
{% block header %} {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="container">
            <div class="row">
                {{ content() }}
            </div>
        </div>
    </div>
</div>
    
{% endblock %}

{% block footer %} {% endblock %}
{% block scriptMainFooter %} {% endblock %} 
{% block scriptFooter %} {% endblock %} 