<div class="row">
    <div class="col-12">
        <div class="text-welcome" style="padding-top: 230px;">
            <h1 style="margin:0;padding:0;font-size:5.3em;">Phalcon Framework</h1>
            <h2 style="margin:0;padding:0;font-size:1.6em;">CodeStep โค้ดสเต็ป - เรียนรู้ออนไลน์ สะดวก ง่าย เข้าถึงได้ทุกที่</h2>
            <div class="text-button">
                <a href="https://drivesoft.co.th" style="font-size:0.8em;text-decoration:none;">Use it for Free</a>
                <a href="https://drivesoft.co.th" style="font-size:0.8em;text-decoration:none;">Software Developer</a>
            </h3>
        </div>
    </div>
</div>